Console.WriteLine("Введите три числа, и узнайте, ");
Console.WriteLine("какое из них имеет максимальное значение.");
Console.Write("Введите первое число и нажмите ENTER: ");
int num1 = int.Parse(Console.ReadLine());
Console.Write("Введите второе число и нажмите ENTER: ");
int num2 = int.Parse(Console.ReadLine());
Console.Write("Введите третье число и нажмите ENTER: ");
int num3 = int.Parse(Console.ReadLine());
int maxN = 0;
if (num1 > maxN) maxN = num1;
if (num2 > maxN) maxN = num2;
if (num3 > maxN) maxN = num3;
Console.Write("Максимальное число " + maxN);